domain: forge.k8s.nicwaller.com
storageClass: local-path
storageSize: 10Gi
adminUsername: gitadmin
# adminPassword: generated and stable if omitted
# runnerCount: 1          # number of ephemeral action runners; set to 0 to disable
runnerCount: 2
